openapi: 3.0.1
info:
  title: Gestion de proceso de adquisicion de acero
  description: Servicio para gestionar el proceso de adquisicion de acero en una empresa de forja de acero.
  version: 0.0.1

servers:
  - url: http://localhost:8080
    description: Servidor local

tags:
  - name: Compra

paths:
  /compra:
    post:
      tags:
        - Compra
      summary: Realizar una compra
      description: Realiza una compra de acero.
      operationId: realizarCompra
      requestBody:
        description: Contiene los datos de la solicitud de la compra así como datos del proveedor al que se le realizó la compra
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Compra'
      responses:
        '201':
          description: Compra realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Compra'
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
    get:
      tags:
        - Compra
      summary: Obtener todas las compras
      description: Obtiene todas las compras realizadas.
      operationId: obtenerCompras
      responses:
        '200':
          description: Compras obtenidas con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Compra'
        '404':
          description: No se encontraron compras
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'

components:
  schemas:
    Compra:

    ResponseCode: