openapi: 3.0.1
info:
  title: Gestión del Proceso de Adquisición de Acero
  description: API para gestionar el proceso de adquisición y distribución de acero en una empresa de forja de acero, incluyendo la creación, actualización, y seguimiento de compras y distribuciones.
  version: 0.0.1
servers:
- url: http://localhost:8080
  description: Servidor local para pruebas

tags:
- name: Purchase
  description: Operaciones relacionadas con la adquisición de acero.
- name: Return
  description: Operaciones relacionadas con la devolución de acero.

paths:

  /return:
    post:
      tags:
        - Return
      summary: Realizar una nueva solicitud de devolución de acero.
      description: Crea una nueva solicitud de devolución de acero, especificando los detalles de la devolución y el proveedor.
      operationId: postDevolucion
      requestBody:
        description: Datos necesarios para crear la devolución, incluyendo detalles del proveedor.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Return'
      responses:
        '201':
          description: Devolución creada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Return'
        '400':
          description: Solicitud incorrecta o datos inválidos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'

    get:
      tags:
        - Return
      summary: Obtener una lista de devoluciones o una sola devolucion.
      description: Devuelve una lista de devoluciones o una sola devolucion si el idReturn es especificado.
      operationId: getReturns
      parameters:
        - name: id
          in: query
          description: Identificador de la devolución a obtener.
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Devolución(es) obtenida(s) exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Return'
        '404':
          description: Devolución no encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'

    
    put:
      tags:
        - Return
      summary: Actualizar el estado de una devolución
      description: Actualiza el estado de una devolución, especificando el nuevo estado y, en caso de ser necesario, el motivo.
      operationId: putDevolucion
      requestBody:
        description: Datos necesarios para actualizar la devolución, incluyendo el nuevo estado y, en caso de ser necesario, el motivo.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReturn'
      responses:
        '200':
          description: Return actualizada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Return'
        '400':
          description: Solicitud incorrecta o datos inválidos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '404':
          description: Devolución no encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
    
    delete:
      tags:
        - Return
      summary: Eliminar una devolución
      description: Elimina una devolución existente, especificando su identificador.
      operationId: deleteDevolucion
      parameters:
        - name: id
          in: query
          description: Identificador de la devolución a eliminar.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Devolución eliminada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '404':
          description: Devolución no encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
  
  /purchase:
    post:
      tags:
        - Purchase
      summary: Realizar una nueva compra de acero.
      description: Crea una nueva compra de acero, especificando los detalles de la compra y el proveedor.
      operationId: postCompra
      requestBody:
        description: Datos necesarios para crear la compra, incluyendo detalles del proveedor.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Purchase'
      responses:
        '201':
          description: Compra creada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purchase'
        '400':
          description: Solicitud incorrecta o datos inválidos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
    
    get:
      tags:
        - Purchase
      summary: Obtener una lista de compras o una sola compra.
      description: Devuelve una lista de compras o una sola compra si el idPurchase es especificado.
      operationId: getCompras
      parameters:
        - name: id
          in: query
          description: Identificador de la compra a obtener.
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Compra(s) obtenida(s) exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purchase'
        '404':
          description: Compra no encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
    
    put:
      tags:
        - Purchase
      summary: Actualizar la fecha de entrega, estatus y problema de una compra
      description: Actualiza la fecha de entrega, estatus y problema de una compra, especificando la nueva fecha de entrega, el nuevo estatus y, en caso de ser necesario, el problema.
      operationId: purchaseUpdate
      requestBody:
        description: Datos necesarios para actualizar la compra, incluyendo la nueva fecha de entrega, el nuevo estatus y, en caso de ser necesario, el problema.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePurchase'
      responses:
        '200':
          description: Compra actualizada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purchase'
        '400':
          description: Solicitud incorrecta o datos inválidos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '404':
          description: Compra no encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'

    delete:
      tags:
        - Purchase
      summary: Eliminar una compra
      description: Elimina una compra existente, especificando su identificador.
      operationId: deleteCompra
      parameters:
        - name: id
          in: query
          description: Identificador de la compra a eliminar.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Compra eliminada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '404':
          description: Compra no encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCode'

components:
  schemas:

    Purchase:
      type: object
      properties:

        id:
          type: integer
          format: int64

        suplier:
          type: string

        amount:
          type: number
          format: double

        orderDate:
          type: string
          format: date

        deliveryDate:
          type: string
          format: date

        status:
          type: string

        totalPrice:
          type: number
          format: double

        availability:
          type: boolean
          
        shippingDate:
          type: string
          format: date
      
      example:
          id: 123
          suplier: "Brasil"
          amount: 1000.0
          orderDate: "2024-09-17"
          deliveryDate: "2024-11-17"
          status: "En proceso"
          totalPrice: 50000.0
          availability: true
          problem: "Retraso en aduanas"
          shippingDate: "2024-10-01"

    UpdatePurchase:
      type: object
      properties:

        deliveryDate:
          type: string
          format: date

        status:
          type: string

        problem:
          type: string

    Return:
      type: object
      properties:

        idReturn:
          type: integer
          format: int64

        suplier:
          type: string

        amount:
          type: number
          format: double

        returnDate:
          type: string
          format: date

        status:
          type: string

        reason:
          type: string

        shippingDate:
          type: string
          format: date
      
    UpdateReturn:
      type: object
      properties:

        idReturn:
          type: integer
          format: int64

        status:
          type: string

    ResponseCode:
      type: object
      properties:

        code:
          type: string
        message:
          type: string
          
      example:
        code: "404"
        message: "Recurso no encontrado"